### ISSUE TITLE
ボタンの背景色が白で固定されている

### ISSUE THREAD

**Issue by masachika-kamada** [tsuzukia21/st-img-pastebutton#1]
素晴らしいコンポーネントの公開ありがとうございます。
以下のような機能改善があると嬉しいです。ご検討いただけますと幸いです。

* **現状**
  ダークテーマを使用している場合、ボタンの背景が白で浮いてしまう

* **理想**
  テーマ変更時に背景がインタラクティブに変化

![image](https://github.com/tsuzukia21/st-img-pastebutton/assets/63488322/7654168f-4c45-48ae-96f0-dc1b483065f6)

**Comment by tsuzukia21** [comment]
こんにちは！拙いコードですみませんが、素晴らしいプルリクエストをありがとうございます。マージさせて頂きました。これからもぜひご協力お願いします！
